apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  namespace: samza-router
  name: interrogator
  labels:
    app: interrogator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interrogator
  template:
    metadata:
      labels:
        app: interrogator
    spec:
      containers:
      - name: interrogator
        image: nginx:1.7.9
        ports:
        - containerPort: 80
